const Unknown='Unknown';
const bleachCharacters = [
  ['Ichigo Kurosaki','Male',15,'Zangetsu','Substitute Soul Reaper','Agent of the Shinigami','Karakura Town','Human'],
  ['Rukia Kuchiki','Female',150,'Sode no Shirayuki','Gotei 13','Agent of the Shinigami','Soul Society','Soul'],
  ['Orihime Inoue','Female',15,'Shun Shun Rikka','Human','Arrancar: The Arrival','Karakura Town','Human'],
  ['Uryu Ishida','Male',15,'Heilig Bogen','Quincy','Agent of the Shinigami','Karakura Town','Quincy'],
  ['Yasutora Sado','Male',15,'Brazo Derecha de Gigante','Human','Agent of the Shinigami','Karakura Town','Fullbringer'],
  ['Renji Abarai','Male',150,'Zabimaru','Gotei 13','Soul Society','Rukongai','Soul'],
  ['Byakuya Kuchiki','Male',200,'Senbonzakura','Gotei 13','Soul Society','Soul Society','Soul'],
  ['Toshiro Hitsugaya','Male',110,'Hyorinmaru','Gotei 13','Soul Society','Soul Society','Soul'],
  ['Kenpachi Zaraki','Male',200,'Nozarashi','Gotei 13','Soul Society','Rukongai','Soul'],
  ['Sosuke Aizen','Male',300,'Kyoka Suigetsu','Arrancar','Arrancar: The Arrival','Soul Society','Soul'],
  ['Yoruichi Shihoin','Female',300,'Shunko','Gotei 13','Soul Society','Soul Society','Soul'],
  ['Kisuke Urahara','Male',500,'Benihime','Shopkeeper','Agent of the Shinigami','Soul Society','Soul'],
  ['Mayuri Kurotsuchi','Male',300,'Ashisogi Jizo','Gotei 13','Soul Society','Soul Society','Soul'],
  ['Shinji Hirako','Male',200,'Sakanade','Visored','Arrancar: The Arrival','Soul Society','Soul'],
  ['Ulquiorra Cifer','Male',Unknown,'Murcielago','Espada','Arrancar: The Arrival','Hueco Mundo','Arrancar'],
  ['Grimmjow Jaegerjaquez','Male',Unknown,'Pantera','Espada','Arrancar: The Arrival','Hueco Mundo','Arrancar'],
  ['Nelliel Tu Odelschwanck','Female',Unknown,'Gamuza','Espada','Arrancar: The Arrival','Hueco Mundo','Arrancar'],
  ['Jugram Haschwalth','Male',Unknown,'The Balance','Sternritter','Thousand-Year Blood War','Wandenreich','Quincy'],
  ['Yhwach','Male',1200,'The Almighty','Wandenreich','Thousand-Year Blood War','Wandenreich','Quincy'],
  ['Genryusai Shigekuni Yamamoto','Male',2100,'Ryujin Jakka','Gotei 13','Soul Society','Soul Society','Soul'],
['Sajin Komamura','Male',200,'Tenken','Gotei 13','Soul Society','Soul Society','Soul','Brown'],
['Soi Fon','Female',200,'Suzumebachi','Gotei 13','Soul Society','Soul Society','Soul','Black'],
['Retsu Unohana','Female',2000,'Minazuki','Gotei 13','Soul Society','Soul Society','Soul','Black'],
['Jushiro Ukitake','Male',300,'Sogyo no Kotowari','Gotei 13','Soul Society','Soul Society','Soul','White'],
['Shunsui Kyoraku','Male',300,'Katen Kyokotsu','Gotei 13','Soul Society','Soul Society','Soul','Brown'],
['Rojuro Otoribashi','Male',200,'Kinshara','Visored','Arrancar: The Arrival','Soul Society','Soul','Blond'],
['Kensei Muguruma','Male',200,'Tekken Tachikaze','Visored','Arrancar: The Arrival','Soul Society','Soul','White'],
['Hiyori Sarugaki','Female',200,'Kubikiri Orochi','Visored','Arrancar: The Arrival','Soul Society','Soul','Blond'],
['Love Aikawa','Male',200,'Tengumaru','Visored','Arrancar: The Arrival','Soul Society','Soul','Black'],
['Lisa Yadomaru','Female',200,'Haguro Tonbo','Visored','Arrancar: The Arrival','Soul Society','Soul','Black'],
['Isshin Kurosaki','Male',200,'Engetsu','Shinigami','Agent of the Shinigami','Soul Society','Soul','Black'],
['Masaki Kurosaki','Female','Unknown','Unknown','Quincy','Backstory','Karakura Town','Quincy','Black'],
['Ryuken Ishida','Male','Unknown','Unknown','Quincy','Backstory','Karakura Town','Quincy','Black'],
['Soken Ishida','Male','Unknown','Unknown','Quincy','Backstory','Karakura Town','Quincy','White'],
['Bazz-B','Male','Unknown','The Heat','Sternritter','Thousand-Year Blood War','Wandenreich','Quincy','Red'],
['Askin Nakk Le Vaar','Male','Unknown','The Deathdealing','Sternritter','Thousand-Year Blood War','Wandenreich','Blond'],
['Lille Barro','Male','Unknown','The X-Axis','Sternritter','Thousand-Year Blood War','Wandenreich','Quincy','Black'],
['Gerard Valkyrie','Male','Unknown','The Miracle','Sternritter','Thousand-Year Blood War','Wandenreich','Quincy','Blond'],
['Giselle Gewelle','Female','Unknown','The Zombie','Sternritter','Thousand-Year Blood War','Wandenreich','Quincy','Blond'],
['Bambietta Basterbine','Female','Unknown','The Explode','Sternritter','Thousand-Year Blood War','Wandenreich','Quincy','Black'],
['Candice Catnipp','Female','Unknown','The Thunderbolt','Sternritter','Thousand-Year Blood War','Wandenreich','Quincy','Blond'],
['Momo Hinamori','Female',150,'Tobiume','Gotei 13','Soul Society','Soul Society','Soul','Brown'],
['Izuru Kira','Male',200,'Wabisuke','Gotei 13','Soul Society','Soul Society','Soul','Blond'],
['Ikkaku Madarame','Male',200,'Hozukimaru','Gotei 13','Soul Society','Rukongai','Soul','Black'],
['Yumichika Ayasegawa','Male',200,'Ruri iro Kujaku','Gotei 13','Soul Society','Rukongai','Soul','Black'],
['Nemu Kurotsuchi','Female',20,'Unknown','Gotei 13','Soul Society','Soul Society','Artificial Soul','Black'],
['Tetsuzaemon Iba','Male',200,'Unknown','Gotei 13','Soul Society','Soul Society','Soul','Black'],
['Marechiyo Omaeda','Male',200,'Gegetsuburi','Gotei 13','Soul Society','Soul Society','Soul','Black'],
['Chojiro Sasakibe','Male',2000,'Gonryomaru','Gotei 13','Soul Society','Soul Society','Soul','Blond'],
['Kukaku Shiba','Female',200,'Unknown','Shiba Clan','Soul Society','Soul Society','Soul','Black'],
['Ganju Shiba','Male','Unknown','Earth manipulation','Shiba Clan','Soul Society','Soul Society','Human','Black'],
['Coyote Starrk','Male','Unknown','Los Lobos','Espada','Arrancar: The Arrival','Hueco Mundo','Arrancar','Black'],
['Nnoitra Gilga','Male','Unknown','Santa Teresa','Espada','Arrancar: The Arrival','Hueco Mundo','Arrancar','Black'],
['Tier Harribel','Female','Unknown','Tiburon','Espada','Arrancar: The Arrival','Hueco Mundo','Arrancar','Blond'],
].map(([name,gender,age,zanpakuto,faction,arc,origin,species,hairColor])=>({name,gender,age,zanpakuto,faction,arc,origin,species,hairColor:hairColor||'Black',image:`https://tse1.mm.bing.net/th?q=${encodeURIComponent(name+' Bleach')}`}));
