const personaCharacters = [
  { name: 'Joker', gender: 'Male', age: 16, bending: 'Wild Card', faction: 'Phantom Thieves', firstAppearance: 'Persona 5', arc: 'Fool', image: 'assets/joker.png' },
  { name: 'Morgana', gender: 'Male', age: 15, bending: 'Magician', faction: 'Phantom Thieves', firstAppearance: 'Persona 5', arc: 'Magician', image: 'assets/morgana.png' },
  { name: 'Ryuji Sakamoto', gender: 'Male', age: 16, bending: 'Chariot', faction: 'Phantom Thieves', firstAppearance: 'Persona 5', arc: 'Chariot', image: 'assets/ryuji-sakamoto.png' },
  { name: 'Ann Takamaki', gender: 'Female', age: 16, bending: 'Lovers', faction: 'Phantom Thieves', firstAppearance: 'Persona 5', arc: 'Lovers', image: 'assets/ann-takamaki.png' },
  { name: 'Yusuke Kitagawa', gender: 'Male', age: 17, bending: 'Emperor', faction: 'Phantom Thieves', firstAppearance: 'Persona 5', arc: 'Emperor', image: 'assets/yusuke-kitagawa.png' },
  { name: 'Makoto Niijima', gender: 'Female', age: 17, bending: 'Priestess', faction: 'Phantom Thieves', firstAppearance: 'Persona 5', arc: 'Priestess', image: 'assets/makoto-niijima.png' },
  { name: 'Futaba Sakura', gender: 'Female', age: 15, bending: 'Hermit', faction: 'Phantom Thieves', firstAppearance: 'Persona 5', arc: 'Hermit', image: 'assets/futaba-sakura.png' },
  { name: 'Haru Okumura', gender: 'Female', age: 17, bending: 'Empress', faction: 'Phantom Thieves', firstAppearance: 'Persona 5', arc: 'Empress', image: 'assets/haru-okumura.png' },
  { name: 'Goro Akechi', gender: 'Male', age: 17, bending: 'Justice', faction: 'Detective Prince', firstAppearance: 'Persona 5', arc: 'Justice', image: 'assets/goro-akechi.png' },
  { name: 'Kasumi Yoshizawa', gender: 'Female', age: 15, bending: 'Faith', faction: 'Shujin Academy', firstAppearance: 'Persona 5 Royal', arc: 'Faith', image: 'assets/kasumi-yoshizawa.png' },
  { name: 'Sae Niijima', gender: 'Female', age: 27, bending: 'Judgement', faction: 'Public Prosecutor', firstAppearance: 'Persona 5', arc: 'Judgement', image: 'assets/sae-niijima.png' },
  { name: 'Igor', gender: 'Male', age: 1000, bending: 'World', faction: 'Velvet Room', firstAppearance: 'Persona 5 Royal', arc: 'World', image: 'assets/igor.png' },
  { name: 'Caroline', gender: 'Female', age: 10, bending: 'Strength', faction: 'Velvet Room', firstAppearance: 'Persona 5 Royal', arc: 'Strength', image: 'assets/caroline.png' },
  { name: 'Justine', gender: 'Female', age: 10, bending: 'Strength', faction: 'Velvet Room', firstAppearance: 'Persona 5 Royal', arc: 'Strength', image: 'assets/justine.png' },
  { name: 'Sojiro Sakura', gender: 'Male', age: 46, bending: 'Hierophant', faction: 'Cafe Leblanc', firstAppearance: 'Persona 5', arc: 'Hierophant', image: 'assets/sojiro-sakura.png' },
  { name: 'Munehisa Iwai', gender: 'Male', age: 38, bending: 'Hanged Man', faction: 'Untouchable', firstAppearance: 'Persona 5', arc: 'Hanged Man', image: 'assets/munehisa-iwai.png' },
  { name: 'Tae Takemi', gender: 'Female', age: 28, bending: 'Death', faction: 'Yongen-Jaya Clinic', firstAppearance: 'Persona 5', arc: 'Death', image: 'assets/tae-takemi.png' },
  { name: 'Sadayo Kawakami', gender: 'Female', age: 26, bending: 'Temperance', faction: 'Shujin Academy', firstAppearance: 'Persona 5', arc: 'Temperance', image: 'assets/sadayo-kawakami.png' },
  { name: 'Takuto Maruki', gender: 'Male', age: 32, bending: 'Councillor', faction: 'Shujin Academy', firstAppearance: 'Persona 5 Royal', arc: 'Councillor', image: 'assets/takuto-maruki.png' },
  { name: 'Masayoshi Shido', gender: 'Male', age: 48, bending: 'Emperor', faction: 'Japanese Government', firstAppearance: 'Persona 5', arc: 'Emperor', image: 'assets/masayoshi-shido.png' },
  { name: 'Makoto Yuki', gender: 'Male', age: 17, bending: 'Wild Card', faction: 'SEES', firstAppearance: 'Persona 3', arc: 'Fool', image: 'assets/makoto-yuki.png' },
  { name: 'Yukari Takeba', gender: 'Female', age: 16, bending: 'Lovers', faction: 'SEES', firstAppearance: 'Persona 3', arc: 'Lovers', image: 'assets/yukari-takeba.png' },
  { name: 'Junpei Iori', gender: 'Male', age: 16, bending: 'Magician', faction: 'SEES', firstAppearance: 'Persona 3', arc: 'Magician', image: 'assets/junpei-iori.png' },
  { name: 'Akihiko Sanada', gender: 'Male', age: 17, bending: 'Emperor', faction: 'SEES', firstAppearance: 'Persona 3', arc: 'Emperor', image: 'assets/akihiko-sanada.png' },
  { name: 'Mitsuru Kirijo', gender: 'Female', age: 17, bending: 'Empress', faction: 'SEES', firstAppearance: 'Persona 3', arc: 'Empress', image: 'assets/mitsuru-kirijo.png' },
  { name: 'Fuuka Yamagishi', gender: 'Female', age: 16, bending: 'Priestess', faction: 'SEES', firstAppearance: 'Persona 3', arc: 'Priestess', image: 'assets/fuuka-yamagishi.png' },
  { name: 'Aigis', gender: 'Female', age: 10, bending: 'Aeon', faction: 'SEES', firstAppearance: 'Persona 3', arc: 'Aeon', image: 'assets/aigis.png' },
  { name: 'Ken Amada', gender: 'Male', age: 10, bending: 'Justice', faction: 'SEES', firstAppearance: 'Persona 3', arc: 'Justice', image: 'assets/ken-amada.png' },
  { name: 'Koromaru', gender: 'Male', age: 7, bending: 'Strength', faction: 'SEES', firstAppearance: 'Persona 3', arc: 'Strength', image: 'assets/koromaru.png' },
  { name: 'Shinjiro Aragaki', gender: 'Male', age: 17, bending: 'Hierophant', faction: 'SEES', firstAppearance: 'Persona 3', arc: 'Hierophant', image: 'assets/shinjiro-aragaki.png' },
  { name: 'Elizabeth', gender: 'Female', age: 1000, bending: 'Death', faction: 'Velvet Room', firstAppearance: 'Persona 3', arc: 'Death', image: 'assets/elizabeth.png' },
  { name: 'Shuji Ikutsuki', gender: 'Male', age: 31, bending: 'Hierophant', faction: 'Gekkoukan High School', firstAppearance: 'Persona 3', arc: 'Hierophant', image: 'assets/shuji-ikutsuki.png' },
  { name: 'Ryoji Mochizuki', gender: 'Male', age: 17, bending: 'Death', faction: 'Gekkoukan High School', firstAppearance: 'Persona 3', arc: 'Death', image: 'assets/ryoji-mochizuki.png' },
  { name: 'Takaya Sakaki', gender: 'Male', age: 18, bending: 'Moon', faction: 'Strega', firstAppearance: 'Persona 3', arc: 'Moon', image: 'assets/takaya-sakaki.png' },
  { name: 'Nyx Avatar', gender: 'Unknown', age: 1000, bending: 'Death', faction: 'Apathy Syndrome', firstAppearance: 'Persona 3', arc: 'Death', image: 'assets/nyx-avatar.png' },
  { name: 'Yu Narukami', gender: 'Male', age: 16, bending: 'Wild Card', faction: 'Investigation Team', firstAppearance: 'Persona 4', arc: 'Fool', image: 'assets/yu-narukami.png' },
  { name: 'Yosuke Hanamura', gender: 'Male', age: 16, bending: 'Magician', faction: 'Investigation Team', firstAppearance: 'Persona 4', arc: 'Magician', image: 'assets/yosuke-hanamura.png' },
  { name: 'Chie Satonaka', gender: 'Female', age: 16, bending: 'Chariot', faction: 'Investigation Team', firstAppearance: 'Persona 4', arc: 'Chariot', image: 'assets/chie-satonaka.png' },
  { name: 'Yukiko Amagi', gender: 'Female', age: 16, bending: 'Priestess', faction: 'Investigation Team', firstAppearance: 'Persona 4', arc: 'Priestess', image: 'assets/yukiko-amagi.png' },
  { name: 'Kanji Tatsumi', gender: 'Male', age: 15, bending: 'Emperor', faction: 'Investigation Team', firstAppearance: 'Persona 4', arc: 'Emperor', image: 'assets/kanji-tatsumi.png' },
  { name: 'Rise Kujikawa', gender: 'Female', age: 15, bending: 'Lovers', faction: 'Investigation Team', firstAppearance: 'Persona 4', arc: 'Lovers', image: 'assets/rise-kujikawa.png' },
  { name: 'Naoto Shirogane', gender: 'Female', age: 16, bending: 'Fortune', faction: 'Investigation Team', firstAppearance: 'Persona 4', arc: 'Fortune', image: 'assets/naoto-shirogane.png' },
  { name: 'Teddie', gender: 'Male', age: 15, bending: 'Star', faction: 'Investigation Team', firstAppearance: 'Persona 4', arc: 'Star', image: 'assets/teddie.png' },
  { name: 'Marie', gender: 'Female', age: 16, bending: 'Aeon', faction: 'Velvet Room', firstAppearance: 'Persona 4', arc: 'Aeon', image: 'assets/marie.png' },
  { name: 'Margaret', gender: 'Female', age: 1000, bending: 'Empress', faction: 'Velvet Room', firstAppearance: 'Persona 4', arc: 'Empress', image: 'assets/margaret.png' },
  { name: 'Ryotaro Dojima', gender: 'Male', age: 45, bending: 'Hierophant', faction: 'Inaba Police Department', firstAppearance: 'Persona 4', arc: 'Hierophant', image: 'assets/ryotaro-dojima.png' },
  { name: 'Nanako Dojima', gender: 'Female', age: 7, bending: 'Justice', faction: 'Dojima Family', firstAppearance: 'Persona 4', arc: 'Justice', image: 'assets/nanako-dojima.png' },
  { name: 'Tohru Adachi', gender: 'Male', age: 27, bending: 'Jester', faction: 'Inaba Police Department', firstAppearance: 'Persona 4', arc: 'Jester', image: 'assets/tohru-adachi.png' },
  { name: 'Mitsuo Kubo', gender: 'Male', age: 15, bending: 'Hanged Man', faction: 'Yasogami High School', firstAppearance: 'Persona 4', arc: 'Hanged Man', image: 'assets/mitsuo-kubo.png' },
  { name: 'Taro Namatame', gender: 'Male', age: 48, bending: 'Hanged Man', faction: 'Inaba City Council', firstAppearance: 'Persona 4', arc: 'Hanged Man', image: 'assets/taro-namatame.png' },
  { name: 'Izanami', gender: 'Female', age: 1000, bending: 'World', faction: 'Pursuing Humanity', firstAppearance: 'Persona 4', arc: 'World', image: 'assets/izanami.png' }
];

personaCharacters.forEach(character => {
  character.age = Number(character.age) <= 12 ? 'Child' : Number(character.age) <= 19 ? 'Teenager' : 'Adult';
});
