const jjkCharacters = [
  { name: 'Yuji Itadori', gender: 'Male', age: 15, power: 'Divergent Fist', type: 'Sorcerer', firstArc: 'Fearsome Womb', affiliation: 'Tokyo Jujutsu High', status: 'Alive' },
  { name: 'Megumi Fushiguro', gender: 'Male', age: 15, power: 'Ten Shadows', type: 'Sorcerer', firstArc: 'Fearsome Womb', affiliation: 'Tokyo Jujutsu High', status: 'Alive' },
  { name: 'Nobara Kugisaki', gender: 'Female', age: 16, power: 'Straw Doll', type: 'Sorcerer', firstArc: 'Fearsome Womb', affiliation: 'Tokyo Jujutsu High', status: 'Deceased' },
  { name: 'Satoru Gojo', gender: 'Male', age: 28, power: 'Limitless', type: 'Sorcerer', firstArc: 'Fearsome Womb', affiliation: 'Tokyo Jujutsu High', status: 'Deceased' },
  { name: 'Maki Zenin', gender: 'Female', age: 16, power: 'Heavenly Restriction', type: 'Sorcerer', firstArc: 'Cursed Child', affiliation: 'Tokyo Jujutsu High', status: 'Alive' },
  { name: 'Toge Inumaki', gender: 'Male', age: 17, power: 'Cursed Speech', type: 'Sorcerer', firstArc: 'Cursed Child', affiliation: 'Tokyo Jujutsu High', status: 'Alive' },
  { name: 'Panda', gender: 'Unknown', age: 16, power: 'Cursed Corpse', type: 'Cursed Corpse', firstArc: 'Cursed Child', affiliation: 'Tokyo Jujutsu High', status: 'Alive' },
  { name: 'Yuta Okkotsu', gender: 'Male', age: 17, power: 'Copy', type: 'Sorcerer', firstArc: 'Cursed Child', affiliation: 'Tokyo Jujutsu High', status: 'Alive' },
  { name: 'Kento Nanami', gender: 'Male', age: 28, power: 'Ratio Technique', type: 'Sorcerer', firstArc: 'Fearsome Womb', affiliation: 'Tokyo Jujutsu High', status: 'Deceased' },
  { name: 'Aoi Todo', gender: 'Male', age: 18, power: 'Boogie Woogie', type: 'Sorcerer', firstArc: 'Kyoto Goodwill Event', affiliation: 'Kyoto Jujutsu High', status: 'Alive' },
  { name: 'Mai Zenin', gender: 'Female', age: 16, power: 'Construction', type: 'Sorcerer', firstArc: 'Kyoto Goodwill Event', affiliation: 'Kyoto Jujutsu High', status: 'Deceased' },
  { name: 'Noritoshi Kamo', gender: 'Male', age: 18, power: 'Blood Manipulation', type: 'Sorcerer', firstArc: 'Kyoto Goodwill Event', affiliation: 'Kyoto Jujutsu High', status: 'Alive' },
  { name: 'Kasumi Miwa', gender: 'Female', age: 17, power: 'New Shadow Style', type: 'Sorcerer', firstArc: 'Kyoto Goodwill Event', affiliation: 'Kyoto Jujutsu High', status: 'Alive' },
  { name: 'Momo Nishimiya', gender: 'Female', age: 18, power: 'Tool Manipulation', type: 'Sorcerer', firstArc: 'Kyoto Goodwill Event', affiliation: 'Kyoto Jujutsu High', status: 'Alive' },
  { name: 'Mechamaru', gender: 'Male', age: 17, power: 'Puppet Manipulation', type: 'Sorcerer', firstArc: 'Kyoto Goodwill Event', affiliation: 'Kyoto Jujutsu High', status: 'Deceased' },
  { name: 'Shoko Ieiri', gender: 'Female', age: 28, power: 'Reverse Cursed Technique', type: 'Sorcerer', firstArc: 'Hidden Inventory', affiliation: 'Tokyo Jujutsu High', status: 'Alive' },
  { name: 'Suguru Geto', gender: 'Male', age: 27, power: 'Cursed Spirit Manipulation', type: 'Curse User', firstArc: 'Hidden Inventory', affiliation: 'Curse User', status: 'Deceased' },
  { name: 'Toji Fushiguro', gender: 'Male', age: 27, power: 'Heavenly Restriction', type: 'Sorcerer Killer', firstArc: 'Hidden Inventory', affiliation: 'Independent', status: 'Deceased' },
  { name: 'Masamichi Yaga', gender: 'Male', age: 47, power: 'Cursed Corpse', type: 'Sorcerer', firstArc: 'Fearsome Womb', affiliation: 'Tokyo Jujutsu High', status: 'Deceased' },
  { name: 'Utahime Iori', gender: 'Female', age: 31, power: 'Solo Forbidden Area', type: 'Sorcerer', firstArc: 'Hidden Inventory', affiliation: 'Kyoto Jujutsu High', status: 'Alive' },
  { name: 'Choso', gender: 'Male', age: 150, power: 'Blood Manipulation', type: 'Death Painting', firstArc: 'Death Painting', affiliation: 'Death Paintings', status: 'Deceased' },
  { name: 'Mahito', gender: 'Unknown', age: null, power: 'Idle Transfiguration', type: 'Cursed Spirit', firstArc: 'Fearsome Womb', affiliation: 'Disaster Curses', status: 'Deceased' },
  { name: 'Jogo', gender: 'Unknown', age: null, power: 'Volcanic Curses', type: 'Cursed Spirit', firstArc: 'Fearsome Womb', affiliation: 'Disaster Curses', status: 'Deceased' },
  { name: 'Hanami', gender: 'Unknown', age: null, power: 'Plant Manipulation', type: 'Cursed Spirit', firstArc: 'Kyoto Goodwill Event', affiliation: 'Disaster Curses', status: 'Deceased' },
  { name: 'Dagon', gender: 'Unknown', age: null, power: 'Horizon of the Captivating Skandha', type: 'Cursed Spirit', firstArc: 'Shibuya Incident', affiliation: 'Disaster Curses', status: 'Deceased' },
  { name: 'Ryomen Sukuna', gender: 'Male', age: 1000, power: 'Shrine', type: 'Cursed Object', firstArc: 'Fearsome Womb', affiliation: 'Independent', status: 'Deceased' },
  { name: 'Uraume', gender: 'Unknown', age: 1000, power: 'Ice Formation', type: 'Curse User', firstArc: 'Shibuya Incident', affiliation: 'Sukuna Faction', status: 'Deceased' },
  { name: 'Kenjaku', gender: 'Unknown', age: 1000, power: 'Body Hopping', type: 'Curse User', firstArc: 'Shibuya Incident', affiliation: 'Curse User', status: 'Deceased' },
  { name: 'Hajime Kashimo', gender: 'Male', age: 400, power: 'Mythical Beast Amber', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Deceased' },
  { name: 'Kinji Hakari', gender: 'Male', age: 18, power: 'Idle Death Gamble', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Alive' },
  { name: 'Kirara Hoshi', gender: 'Unknown', age: 18, power: 'Love Rendezvous', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Alive' },
  { name: 'Fumihiko Takaba', gender: 'Male', age: 35, power: 'Comedian', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Alive' },
  { name: 'Hiromi Higuruma', gender: 'Male', age: 36, power: 'Deadly Sentencing', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Alive' },
  { name: 'Hana Kurusu', gender: 'Female', age: 16, power: 'Technique Extinguishment', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Alive' },
  { name: 'Angel', gender: 'Female', age: 1000, power: 'Technique Extinguishment', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Alive' },
  { name: 'Ryu Ishigori', gender: 'Male', age: 400, power: 'Cursed Energy Discharge', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Deceased' },
  { name: 'Yorozu', gender: 'Female', age: 1000, power: 'Construction', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Deceased' },
  { name: 'Reggie Star', gender: 'Male', age: 400, power: 'Receipt Technique', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Deceased' },
  { name: 'Charles Bernard', gender: 'Male', age: 29, power: 'G Warstaff', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Alive' },
  { name: 'Haba', gender: 'Male', age: 30, power: 'Helicopter Hair', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Deceased' },
  { name: 'Hanyu', gender: 'Female', age: 30, power: 'Jet Hair', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Deceased' },
  { name: 'Naoya Zenin', gender: 'Male', age: 27, power: 'Projection Sorcery', type: 'Curse', firstArc: 'Perfect Preparation', affiliation: 'Zenin Clan', status: 'Deceased' },
  { name: 'Naobito Zenin', gender: 'Male', age: 71, power: 'Projection Sorcery', type: 'Sorcerer', firstArc: 'Shibuya Incident', affiliation: 'Zenin Clan', status: 'Deceased' },
  { name: 'Ogi Zenin', gender: 'Male', age: 55, power: 'Blazing Courage', type: 'Sorcerer', firstArc: 'Perfect Preparation', affiliation: 'Zenin Clan', status: 'Deceased' },
  { name: 'Jinichi Zenin', gender: 'Male', age: 40, power: 'Projection Sorcery', type: 'Sorcerer', firstArc: 'Perfect Preparation', affiliation: 'Zenin Clan', status: 'Deceased' },
  { name: 'Ranta Zenin', gender: 'Male', age: 20, power: 'Cursed Eyes', type: 'Sorcerer', firstArc: 'Perfect Preparation', affiliation: 'Zenin Clan', status: 'Deceased' },
  { name: 'Miyo Rokujyuushi', gender: 'Male', age: 60, power: 'Sumo Domain', type: 'Sorcerer', firstArc: 'Culling Game', affiliation: 'Independent', status: 'Alive' },
  { name: 'Miguel Oduol', gender: 'Male', age: 30, power: 'Unknown', type: 'Curse User', firstArc: 'Cursed Child', affiliation: 'Independent', status: 'Alive' },
  { name: 'Larue', gender: 'Male', age: 30, power: 'The Hand', type: 'Curse User', firstArc: 'Cursed Child', affiliation: 'Curse User', status: 'Alive' },
  { name: 'Manami Suda', gender: 'Female', age: 30, power: 'Unknown', type: 'Curse User', firstArc: 'Hidden Inventory', affiliation: 'Curse User', status: 'Deceased' },
  { name: 'Toshihisa Negi', gender: 'Male', age: 30, power: 'Unknown', type: 'Curse User', firstArc: 'Hidden Inventory', affiliation: 'Curse User', status: 'Deceased' },
  { name: 'Mei Mei', gender: 'Female', age: 31, power: 'Black Bird Manipulation', type: 'Sorcerer', firstArc: 'Fearsome Womb', affiliation: 'Independent', status: 'Alive' },
  { name: 'Ui Ui', gender: 'Male', age: 11, power: 'Teleportation', type: 'Sorcerer', firstArc: 'Shibuya Incident', affiliation: 'Independent', status: 'Alive' },
  { name: 'Yuki Tsukumo', gender: 'Female', age: 28, power: 'Star Rage', type: 'Sorcerer', firstArc: 'Death Painting', affiliation: 'Independent', status: 'Deceased' },
  { name: 'Yoshinobu Gakuganji', gender: 'Male', age: 76, power: 'Guitar Amplification', type: 'Sorcerer', firstArc: 'Fearsome Womb', affiliation: 'Kyoto Jujutsu High', status: 'Alive' },
  { name: 'Kiyotaka Ijichi', gender: 'Male', age: 26, power: 'Curtain', type: 'Jujutsu Sorcerer', firstArc: 'Fearsome Womb', affiliation: 'Tokyo Jujutsu High', status: 'Alive' },
  { name: 'Akari Nitta', gender: 'Female', age: 20, power: 'Unknown', type: 'Jujutsu Sorcerer', firstArc: 'Shibuya Incident', affiliation: 'Tokyo Jujutsu High', status: 'Alive' },
  { name: 'Arata Nitta', gender: 'Male', age: 16, power: 'Pain Killer', type: 'Sorcerer', firstArc: 'Shibuya Incident', affiliation: 'Kyoto Jujutsu High', status: 'Alive' },
  { name: 'Junpei Yoshino', gender: 'Male', age: 17, power: 'Moon Dregs', type: 'Civilian', firstArc: 'Fearsome Womb', affiliation: 'Independent', status: 'Deceased' },
  { name: 'Riko Amanai', gender: 'Female', age: 14, power: 'Star Plasma Vessel', type: 'Civilian', firstArc: 'Hidden Inventory', affiliation: 'Tengen Faction', status: 'Deceased' },
  { name: 'Misato Kuroi', gender: 'Female', age: 31, power: 'Unknown', type: 'Civilian', firstArc: 'Hidden Inventory', affiliation: 'Tengen Faction', status: 'Deceased' },
  { name: 'Mimiko Hasaba', gender: 'Female', age: 15, power: 'Voodoo', type: 'Curse User', firstArc: 'Fearsome Womb', affiliation: 'Curse User', status: 'Deceased' },
  { name: 'Nanako Hasaba', gender: 'Female', age: 15, power: 'Photography', type: 'Curse User', firstArc: 'Fearsome Womb', affiliation: 'Curse User', status: 'Deceased' },
  { name: 'Haruta Shigemo', gender: 'Male', age: 20, power: 'Miracles', type: 'Curse User', firstArc: 'Shibuya Incident', affiliation: 'Curse User', status: 'Deceased' },
  { name: 'Eso', gender: 'Male', age: 150, power: 'Rot Technique', type: 'Death Painting', firstArc: 'Death Painting', affiliation: 'Death Paintings', status: 'Deceased' },
  { name: 'Kechizu', gender: 'Unknown', age: 150, power: 'Rot Technique', type: 'Death Painting', firstArc: 'Death Painting', affiliation: 'Death Paintings', status: 'Deceased' },
  { name: 'Finger Bearer', gender: 'Unknown', age: null, power: 'Cursed Energy', type: 'Curse', firstArc: 'Fearsome Womb', affiliation: 'Cursed Spirit', status: 'Deceased' },
  { name: 'Tengen', gender: 'Unknown', age: 1000, power: 'Immortality', type: 'Cursed Object', firstArc: 'Death Painting', affiliation: 'Tengen Faction', status: 'Alive' }
];
