const Unknown='Unknown';
const narutoCharacters = [
  ['Naruto Uzumaki','Male',12,'Wind','Team 7','Academy Entrance','Hidden Leaf','Human'],
  ['Sasuke Uchiha','Male',12,'Fire','Team 7','Academy Entrance','Hidden Leaf','Uchiha'],
  ['Sakura Haruno','Female',12,'Earth','Team 7','Academy Entrance','Hidden Leaf','Human'],
  ['Kakashi Hatake','Male',26,'Lightning','Team 7','Land of Waves','Hidden Leaf','Human'],
  ['Hinata Hyuga','Female',12,'Lightning','Team 8','Academy Entrance','Hidden Leaf','Hyuga'],
  ['Shikamaru Nara','Male',12,'Shadow','Team 10','Academy Entrance','Hidden Leaf','Nara'],
  ['Ino Yamanaka','Female',12,'Mind','Team 10','Academy Entrance','Hidden Leaf','Yamanaka'],
  ['Choji Akimichi','Male',12,'Earth','Team 10','Academy Entrance','Hidden Leaf','Akimichi'],
  ['Rock Lee','Male',13,'None','Team Guy','Chunin Exams','Hidden Leaf','Human'],
  ['Neji Hyuga','Male',13,'Wind','Team Guy','Chunin Exams','Hidden Leaf','Hyuga'],
  ['Gaara','Male',12,'Wind','Team Baki','Chunin Exams','Hidden Sand','Jinchuriki'],
  ['Jiraiya','Male',50,'Fire','Three Legendary Sannin','Search for Tsunade','Hidden Leaf','Human'],
  ['Tsunade','Female',51,'Medical','Hokage','Search for Tsunade','Hidden Leaf','Senju'],
  ['Orochimaru','Male',50,'Earth','Three Legendary Sannin','Chunin Exams','Hidden Leaf','Human'],
  ['Itachi Uchiha','Male',17,'Fire','Akatsuki','Search for Tsunade','Hidden Leaf','Uchiha'],
  ['Deidara','Male',19,'Earth','Akatsuki','Kazekage Rescue','Hidden Stone','Human'],
  ['Sasori','Male',35,'Earth','Akatsuki','Kazekage Rescue','Hidden Sand','Human'],
  ['Kisame Hoshigaki','Male',29,'Water','Akatsuki','Kazekage Rescue','Hidden Mist','Human'],
  ['Madara Uchiha','Male',90,'Fire','Uchiha Clan','Fourth Shinobi War','Hidden Leaf','Uchiha'],
  ['Obito Uchiha','Male',31,'Fire','Akatsuki','Fourth Shinobi War','Hidden Leaf','Uchiha'],
['Might Guy','Male',26,'None','Team Guy','Academy Entrance','Hidden Leaf','Human','Black'],
['Asuma Sarutobi','Male',27,'Wind','Team 10','Academy Entrance','Hidden Leaf','Sarutobi','Black'],
['Kurenai Yuhi','Female',27,'Genjutsu','Team 8','Academy Entrance','Hidden Leaf','Human','Red'],
['Iruka Umino','Male',22,'Unknown','Academy','Academy Entrance','Hidden Leaf','Human','Brown'],
['Hiruzen Sarutobi','Male',68,'Fire','Hokage','Chunin Exams','Hidden Leaf','Sarutobi','White'],
['Minato Namikaze','Male',24,'Wind','Hokage','Konoha Crush','Hidden Leaf','Human','Blond'],
['Kushina Uzumaki','Female',24,'Chakra chains','Uzumaki Clan','Nine-Tails Attack','Hidden Leaf','Uzumaki','Red'],
['Hashirama Senju','Male',38,'Wood','Hokage','Backstory','Hidden Leaf','Senju','Black'],
['Tobirama Senju','Male',35,'Water','Hokage','Backstory','Hidden Leaf','Senju','White'],
['Danzo Shimura','Male',72,'Wind','Root','Five Kage Summit','Hidden Leaf','Human','White'],
['Sai','Male',17,'Ink','Team 7','Tenchi Bridge','Hidden Leaf','Human','Black'],
['Yamato','Male',26,'Wood','Team 7','Tenchi Bridge','Hidden Leaf','Human','Brown'],
['Kabuto Yakushi','Male',19,'Medical','Sound Four','Chunin Exams','Hidden Leaf','Sage','Gray'],
['Kimimaro','Male',15,'Bone','Sound Four','Chunin Exams','Hidden Mist','Kaguya','White'],
['Haku','Male',15,'Ice','Zabuza Group','Land of Waves','Hidden Mist','Human','Black'],
['Zabuza Momochi','Male',26,'Water','Seven Ninja Swordsmen','Land of Waves','Hidden Mist','Human','Black'],
['Konan','Female',35,'Paper','Akatsuki','Pain Assault','Hidden Rain','Human','Blue'],
['Nagato','Male',35,'Rinnegan','Akatsuki','Pain Assault','Hidden Rain','Uzumaki','Red'],
['Yahiko','Male',25,'Water','Akatsuki','Pain Assault','Hidden Rain','Human','Orange'],
['Hidan','Male',22,'Unknown','Akatsuki','Kazekage Rescue','Hidden Hot Water','Human','Gray'],
['Kakuzu','Male',91,'Earth','Akatsuki','Kazekage Rescue','Takigakure','Human','Black'],
['Karin','Female',16,'Healing','Taka','Five Kage Summit','Hidden Grass','Uzumaki','Red'],
['Suigetsu Hozuki','Male',16,'Water','Taka','Five Kage Summit','Hidden Mist','Hozuki','Blue'],
['Jugo','Male',18,'Unknown','Taka','Five Kage Summit','Unknown','Human','Orange'],
['Killer B','Male',36,'Lightning','Team Samui','Five Kage Summit','Hidden Cloud','Jinchuriki','Blond'],
['Darui','Male',26,'Lightning','Hidden Cloud','Five Kage Summit','Hidden Cloud','Human','White'],
['Onoki','Male',79,'Earth','Hidden Stone','Fourth Shinobi War','Hidden Stone','Human','White'],
['Mei Terumi','Female',31,'Water','Hidden Mist','Five Kage Summit','Hidden Mist','Human','Brown'],
['A','Male',47,'Lightning','Hidden Cloud','Five Kage Summit','Hidden Cloud','Human','Blond'],
['Temari','Female',15,'Wind','Team Baki','Chunin Exams','Hidden Sand','Human','Blond'],
['Kankuro','Male',15,'Puppet','Team Baki','Chunin Exams','Hidden Sand','Human','Brown'],
['Kiba Inuzuka','Male',12,'Beast mimicry','Team 8','Academy Entrance','Hidden Leaf','Inuzuka','Brown'],
['Shino Aburame','Male',12,'Insects','Team 8','Academy Entrance','Hidden Leaf','Aburame','Black'],
['Tenten','Female',13,'Weapon mastery','Team Guy','Chunin Exams','Hidden Leaf','Human','Brown'],
['Konohamaru Sarutobi','Male',8,'Fire','Team Ebisu','Chunin Exams','Hidden Leaf','Sarutobi','Brown'],
].map(([name,gender,age,nature,faction,arc,origin,species,hairColor])=>({name,gender,age,nature,faction,arc,origin,species,hairColor:hairColor||'Black',image:`https://tse1.mm.bing.net/th?q=${encodeURIComponent(name+' Naruto')}`}));

const narutoRanks = {
  'Naruto Uzumaki':'Hokage','Sasuke Uchiha':'Missing-nin','Sakura Haruno':'Jonin',
  'Kakashi Hatake':'Hokage','Hinata Hyuga':'Chunin','Shikamaru Nara':'Chunin',
  'Ino Yamanaka':'Chunin','Choji Akimichi':'Chunin','Rock Lee':'Chunin','Neji Hyuga':'Jonin',
  'Gaara':'Kazekage','Jiraiya':'Sannin','Tsunade':'Hokage','Orochimaru':'Sannin',
  'Itachi Uchiha':'Missing-nin','Deidara':'S-rank missing-nin','Sasori':'S-rank missing-nin',
  'Kisame Hoshigaki':'S-rank missing-nin','Madara Uchiha':'Legendary shinobi',
  'Obito Uchiha':'Missing-nin','Might Guy':'Jonin','Asuma Sarutobi':'Jonin','Kurenai Yuhi':'Jonin',
  'Iruka Umino':'Chunin','Hiruzen Sarutobi':'Hokage','Minato Namikaze':'Hokage',
  'Kushina Uzumaki':'Jonin','Hashirama Senju':'Hokage','Tobirama Senju':'Hokage',
  'Danzo Shimura':'Jonin','Sai':'Chunin','Yamato':'Jonin','Kabuto Yakushi':'Missing-nin',
  'Kimimaro':'S-rank missing-nin','Haku':'Missing-nin','Zabuza Momochi':'S-rank missing-nin',
  'Konan':'S-rank missing-nin','Nagato':'S-rank missing-nin','Yahiko':'Jonin',
  'Hidan':'S-rank missing-nin','Kakuzu':'S-rank missing-nin','Karin':'Genin',
  'Suigetsu Hozuki':'Missing-nin','Jugo':'Missing-nin','Killer B':'Jinchuriki',
  'Darui':'Jonin','Onoki':'Tsuchikage','Mei Terumi':'Mizukage','A':'Raikage',
  'Temari':'Jonin','Kankuro':'Jonin','Kiba Inuzuka':'Chunin','Shino Aburame':'Chunin',
  'Tenten':'Chunin','Konohamaru Sarutobi':'Jonin'
};

narutoCharacters.forEach(character => {
  character.rank = narutoRanks[character.name] || 'Jonin';
});
