const opmCharacters = [
  { name: 'Saitama', gender: 'Male', age: 25, bending: 'Hero', faction: 'Hero Association', birthplace: 'City Z', arc: 'Hero Hunter', heroClass: 'A39', image: 'assets/saitama.png' },
  { name: 'Genos', gender: 'Male', age: 19, bending: 'Cyborg', faction: 'Hero Association', birthplace: 'City Z', arc: 'Hero Hunter', heroClass: 'S14', image: 'assets/genos.png' },
  { name: 'Tatsumaki', gender: 'Female', age: 28, bending: 'Esper', faction: 'Hero Association', birthplace: 'City B', arc: 'Monster Association', heroClass: 'S2', image: 'assets/tatsumaki.png' },
  { name: 'Fubuki', gender: 'Female', age: 23, bending: 'Esper', faction: 'Blizzard Group', birthplace: 'City B', arc: 'Hero Hunter', heroClass: 'B1', image: 'assets/fubuki.png' },
  { name: 'Bang', gender: 'Male', age: 81, bending: 'Martial Artist', faction: 'Hero Association', birthplace: 'City Q', arc: 'Monster Association', heroClass: 'S3', image: 'assets/bang.png' },
  { name: 'King', gender: 'Male', age: 29, bending: 'Human', faction: 'Hero Association', birthplace: 'City H', arc: 'Hero Hunter', heroClass: 'S7', image: 'assets/king.png' },
  { name: 'Mumen Rider', gender: 'Male', age: 25, bending: 'Human', faction: 'Hero Association', birthplace: 'City J', arc: 'Hero Hunter', heroClass: 'C1', image: 'assets/mumen-rider.png' },
  { name: 'Garou', gender: 'Male', age: 18, bending: 'Martial Artist', faction: 'Independent', birthplace: 'City Q', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/garou.png' },
  { name: 'Speed-o-Sound Sonic', gender: 'Male', age: 25, bending: 'Ninja', faction: 'Independent', birthplace: 'Ninja Village', arc: 'Hero Hunter', heroClass: 'Unranked', image: 'assets/speed-o-sound-sonic.png' },
  { name: 'Atomic Samurai', gender: 'Male', age: 37, bending: 'Swordsman', faction: 'Hero Association', birthplace: 'City A', arc: 'Monster Association', heroClass: 'S4', image: 'assets/atomic-samurai.png' },
  { name: 'Child Emperor', gender: 'Male', age: 10, bending: 'Human', faction: 'Hero Association', birthplace: 'City Y', arc: 'Monster Association', heroClass: 'S5', image: 'assets/child-emperor.png' },
  { name: 'Metal Knight', gender: 'Male', age: 66, bending: 'Robotics', faction: 'Hero Association', birthplace: 'City Z', arc: 'Monster Association', heroClass: 'S6', image: 'assets/metal-knight.png' },
  { name: 'Metal Bat', gender: 'Male', age: 17, bending: 'Human', faction: 'Hero Association', birthplace: 'City Z', arc: 'Monster Association', heroClass: 'S15', image: 'assets/metal-bat.png' },
  { name: 'Watchdog Man', gender: 'Male', age: 30, bending: 'Human', faction: 'Hero Association', birthplace: 'City Q', arc: 'Monster Association', heroClass: 'S12', image: 'assets/watchdog-man.png' },
  { name: 'Flashy Flash', gender: 'Male', age: 25, bending: 'Ninja', faction: 'Hero Association', birthplace: 'Ninja Village', arc: 'Monster Association', heroClass: 'S13', image: 'assets/flashy-flash.png' },
  { name: 'Zombieman', gender: 'Male', age: 30, bending: 'Regeneration', faction: 'Hero Association', birthplace: 'House of Evolution', arc: 'Monster Association', heroClass: 'S8', image: 'assets/zombieman.png' },
  { name: 'Superalloy Darkshine', gender: 'Male', age: 30, bending: 'Human', faction: 'Hero Association', birthplace: 'City T', arc: 'Monster Association', heroClass: 'S11', image: 'assets/superalloy-darkshine.png' },
  { name: 'Puri-Puri Prisoner', gender: 'Male', age: 33, bending: 'Human', faction: 'Hero Association', birthplace: 'City C', arc: 'Monster Association', heroClass: 'S16', image: 'assets/puri-puri-prisoner.png' },
  { name: 'Boros', gender: 'Male', age: 150, bending: 'Alien', faction: 'Dark Matter Thieves', birthplace: 'Dark Matter Ship', arc: 'Alien Conquerors', heroClass: 'Unranked', image: 'assets/boros.png' },
  { name: 'Psykos', gender: 'Female', age: 28, bending: 'Esper', faction: 'Monster Association', birthplace: 'City Q', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/psykos.png' },
  { name: 'Orochi', gender: 'Male', age: 30, bending: 'Monster', faction: 'Monster Association', birthplace: 'Monster Association', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/orochi.png' },
  { name: 'Black Sperm', gender: 'Male', age: 10, bending: 'Monster', faction: 'Monster Association', birthplace: 'Monster Association', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/black-sperm.png' },
  { name: 'Homeless Emperor', gender: 'Male', age: 30, bending: 'Human', faction: 'Monster Association', birthplace: 'City Z', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/homeless-emperor.png' },
  { name: 'Suiryu', gender: 'Male', age: 18, bending: 'Martial Artist', faction: 'Independent', birthplace: 'City A', arc: 'Super Fight', heroClass: 'Unranked', image: 'assets/suiryu.png' },
  { name: 'Snek', gender: 'Male', age: 25, bending: 'Martial Artist', faction: 'Hero Association', birthplace: 'City Z', arc: 'Hero Hunter', heroClass: 'A37', image: 'assets/snek.png' },
  { name: 'Lightning Max', gender: 'Male', age: 25, bending: 'Martial Artist', faction: 'Hero Association', birthplace: 'City H', arc: 'Hero Hunter', heroClass: 'A19', image: 'assets/lightning-max.png' },
  { name: 'Tanktop Master', gender: 'Male', age: 34, bending: 'Human', faction: 'Hero Association', birthplace: 'City T', arc: 'Monster Association', heroClass: 'A16', image: 'assets/tanktop-master.png' },
  { name: 'Tanktop Black Hole', gender: 'Male', age: 30, bending: 'Human', faction: 'Hero Association', birthplace: 'City T', arc: 'Hero Hunter', heroClass: 'Unranked', image: 'assets/tanktop-black-hole.png' },
  { name: 'Pearly', gender: 'Male', age: 20, bending: 'Human', faction: 'Hero Association', birthplace: 'City A', arc: 'Hero Hunter', heroClass: 'Unranked', image: 'assets/pearly.png' },
  { name: 'Spring Mustachio', gender: 'Male', age: 37, bending: 'Swordsman', faction: 'Hero Association', birthplace: 'City A', arc: 'Monster Association', heroClass: 'A33', image: 'assets/spring-mustachio.png' },
  { name: 'Iaian', gender: 'Male', age: 23, bending: 'Swordsman', faction: 'Hero Association', birthplace: 'City A', arc: 'Monster Association', heroClass: 'A2', image: 'assets/iaian.png' },
  { name: 'Bushidrill', gender: 'Male', age: 25, bending: 'Swordsman', faction: 'Hero Association', birthplace: 'City A', arc: 'Monster Association', heroClass: 'A4', image: 'assets/bushidrill.png' },
  { name: 'Okamaitachi', gender: 'Male', age: 25, bending: 'Swordsman', faction: 'Hero Association', birthplace: 'City A', arc: 'Monster Association', heroClass: 'A3', image: 'assets/okamaitachi.png' },
  { name: 'Drive Knight', gender: 'Male', age: 30, bending: 'Cyborg', faction: 'Hero Association', birthplace: 'Unknown', arc: 'Monster Association', heroClass: 'S9', image: 'assets/drive-knight.png' },
  { name: 'Pig God', gender: 'Male', age: 30, bending: 'Human', faction: 'Hero Association', birthplace: 'City unknown', arc: 'Monster Association', heroClass: 'S10', image: 'assets/pig-god.png' },
  { name: 'Flashy Flash’s Master', gender: 'Male', age: 60, bending: 'Ninja', faction: 'Ninja Village', birthplace: 'Ninja Village', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/flashy-flash-master.png' },
  { name: 'Mosquito Girl', gender: 'Female', age: 20, bending: 'Monster', faction: 'House of Evolution', birthplace: 'House of Evolution', arc: 'House of Evolution', heroClass: 'Unranked', image: 'assets/mosquito-girl.png' },
  { name: 'Carnage Kabuto', gender: 'Male', age: 5, bending: 'Monster', faction: 'House of Evolution', birthplace: 'House of Evolution', arc: 'House of Evolution', heroClass: 'Unranked', image: 'assets/carnage-kabuto.png' },
  { name: 'Dr. Genus', gender: 'Male', age: 70, bending: 'Scientist', faction: 'House of Evolution', birthplace: 'City Z', arc: 'House of Evolution', heroClass: 'Unranked', image: 'assets/dr-genus.png' },
  { name: 'Armored Gorilla', gender: 'Male', age: 5, bending: 'Monster', faction: 'House of Evolution', birthplace: 'House of Evolution', arc: 'House of Evolution', heroClass: 'Unranked', image: 'assets/armored-gorilla.png' },
  { name: 'Hammerhead', gender: 'Male', age: 25, bending: 'Human', faction: 'Paradisers', birthplace: 'City Z', arc: 'Hero Hunter', heroClass: 'Unranked', image: 'assets/hammerhead.png' },
  { name: 'Vaccine Man', gender: 'Male', age: 1000, bending: 'Monster', faction: 'Monsters', birthplace: 'City A', arc: 'Hero Hunter', heroClass: 'Unranked', image: 'assets/vaccine-man.png' },
  { name: 'Deep Sea King', gender: 'Male', age: 1000, bending: 'Monster', faction: 'Sea Folk', birthplace: 'Deep Sea', arc: 'Hero Hunter', heroClass: 'Unranked', image: 'assets/deep-sea-king.png' },
  { name: 'Gouketsu', gender: 'Male', age: 1000, bending: 'Monster', faction: 'Monster Association', birthplace: 'Monster Association', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/gouketsu.png' },
  { name: 'Nyan', gender: 'Male', age: 10, bending: 'Monster', faction: 'Monster Association', birthplace: 'Monster Association', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/nyan.png' },
  { name: 'Evil Natural Water', gender: 'Unknown', age: 1000, bending: 'Monster', faction: 'Monster Association', birthplace: 'Monster Association', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/evil-natural-water.png' },
  { name: 'Fuhrer Ugly', gender: 'Male', age: 40, bending: 'Monster', faction: 'Monster Association', birthplace: 'Monster Association', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/fuhrer-ugly.png' },
  { name: 'Rover', gender: 'Unknown', age: 10, bending: 'Monster', faction: 'Monster Association', birthplace: 'Monster Association', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/rover.png' },
  { name: 'Gyoro Gyoro', gender: 'Unknown', age: 1000, bending: 'Monster', faction: 'Monster Association', birthplace: 'Monster Association', arc: 'Monster Association', heroClass: 'Unranked', image: 'assets/gyoro-gyoro.png' }
];
