const frierenCharacters = [
  { name: 'Frieren', gender: 'Female', age: 1000, bending: 'Mage', faction: 'Frieren Party', birthplace: 'Elven Village', arc: 'Journey', mageRank: 'First-Class', image: 'assets/frieren.png' },
  { name: 'Fern', gender: 'Female', age: 18, bending: 'Mage', faction: 'Frieren Party', birthplace: 'Klar Region', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/fern.png' },
  { name: 'Stark', gender: 'Male', age: 18, bending: 'Warrior', faction: 'Frieren Party', birthplace: 'Northern Continent', arc: 'Journey', mageRank: 'Not a mage', image: 'assets/stark.png' },
  { name: 'Himmel', gender: 'Male', age: 76, bending: 'Hero', faction: 'Hero Party', birthplace: 'Northern Continent', arc: 'Demon King', mageRank: 'Not a mage', image: 'assets/himmel.png' },
  { name: 'Heiter', gender: 'Male', age: 100, bending: 'Priest', faction: 'Hero Party', birthplace: 'Northern Continent', arc: 'Demon King', mageRank: 'Not a mage', image: 'assets/heiter.png' },
  { name: 'Eisen', gender: 'Male', age: 100, bending: 'Warrior', faction: 'Hero Party', birthplace: 'Dwarf Village', arc: 'Demon King', mageRank: 'Not a mage', image: 'assets/eisen.png' },
  { name: 'Flamme', gender: 'Female', age: 200, bending: 'Mage', faction: 'Humanity', birthplace: 'Northern Continent', arc: 'Ancient Era', mageRank: 'Not a mage', image: 'assets/flamme.png' },
  { name: 'Serie', gender: 'Female', age: 1000, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Elven Lands', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/serie.png' },
  { name: 'Denken', gender: 'Male', age: 78, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Aüßerst', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/denken.png' },
  { name: 'Ubel', gender: 'Female', age: 20, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/ubel.png' },
  { name: 'Wirbel', gender: 'Male', age: 32, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/wirbel.png' },
  { name: 'Kanne', gender: 'Female', age: 19, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'Third-Class', image: 'assets/kanne.png' },
  { name: 'Lawine', gender: 'Female', age: 20, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'Third-Class', image: 'assets/lawine.png' },
  { name: 'Methode', gender: 'Female', age: 25, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/methode.png' },
  { name: 'Land', gender: 'Male', age: 20, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/land.png' },
  { name: 'Lernen', gender: 'Male', age: 100, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/lernen.png' },
  { name: 'Macht', gender: 'Male', age: 500, bending: 'Demon', faction: 'Gold City', birthplace: 'Demon Lands', arc: 'Golden Land', mageRank: 'Not a mage', image: 'assets/macht.png' },
  { name: 'Solitar', gender: 'Female', age: 500, bending: 'Demon', faction: 'Demon Kind', birthplace: 'Demon Lands', arc: 'Golden Land', mageRank: 'Not a mage', image: 'assets/solitar.png' },
  { name: 'Aura the Guillotine', gender: 'Female', age: 500, bending: 'Demon', faction: 'Demon Kind', birthplace: 'Demon Lands', arc: 'Northern Plateau', mageRank: 'Not a mage', image: 'assets/aura-the-guillotine.png' },
  { name: 'Lugner', gender: 'Male', age: 400, bending: 'Demon', faction: 'Demon Kind', birthplace: 'Demon Lands', arc: 'Northern Plateau', mageRank: 'Not a mage', image: 'assets/lugner.png' },
  { name: 'Qual', gender: 'Male', age: 500, bending: 'Demon', faction: 'Demon Kind', birthplace: 'Demon Lands', arc: 'Journey', mageRank: 'Not a mage', image: 'assets/qual.png' },
  { name: 'Sein', gender: 'Male', age: 30, bending: 'Priest', faction: 'Goddess Church', birthplace: 'Northern Continent', arc: 'Journey', mageRank: 'Not a mage', image: 'assets/sein.png' },
  { name: 'Gorilla Warrior', gender: 'Male', age: 30, bending: 'Warrior', faction: 'Northern Continent', birthplace: 'Northern Continent', arc: 'Journey', mageRank: 'Not a mage', image: 'assets/gorilla-warrior.png' },
  { name: 'Kraft', gender: 'Male', age: 1000, bending: 'Monk', faction: 'Elven Lands', birthplace: 'Elven Lands', arc: 'Journey', mageRank: 'Not a mage', image: 'assets/kraft.png' },
  { name: 'Revolte', gender: 'Male', age: 500, bending: 'Demon', faction: 'Demon Kind', birthplace: 'Demon Lands', arc: 'Northern Plateau', mageRank: 'Not a mage', image: 'assets/revolte.png' },
  { name: 'Rivale', gender: 'Male', age: 500, bending: 'Demon', faction: 'Demon Kind', birthplace: 'Demon Lands', arc: 'Northern Plateau', mageRank: 'Not a mage', image: 'assets/rivale.png' },
  { name: 'Grausam', gender: 'Male', age: 500, bending: 'Demon', faction: 'Demon Kind', birthplace: 'Demon Lands', arc: 'Golden Land', mageRank: 'Not a mage', image: 'assets/graugam.png' },
  { name: 'Genaue', gender: 'Female', age: 60, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/genaue.png' },
  { name: 'Sense', gender: 'Female', age: 70, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/sense.png' },
  { name: 'Richter', gender: 'Male', age: 50, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/richter.png' },
  { name: 'Ehre', gender: 'Female', age: 40, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'First-Class', image: 'assets/ehre.png' },
  { name: 'Schlacht', gender: 'Male', age: 1000, bending: 'Demon', faction: 'Demon Kind', birthplace: 'Demon Lands', arc: 'Ancient Era', mageRank: 'Not a mage', image: 'assets/schlacht.png' },
  { name: 'Demon King', gender: 'Male', age: 1000, bending: 'Demon', faction: 'Demon Kind', birthplace: 'Demon Lands', arc: 'Demon King', mageRank: 'Not a mage', image: 'assets/demon-king.png' },
  { name: 'Edel', gender: 'Female', age: 20, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'Second-Class', image: 'assets/edel.png' },
  { name: 'Scharf', gender: 'Male', age: 20, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'Second-Class', image: 'assets/scharf.png' },
  { name: 'Blei', gender: 'Male', age: 20, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'Third-Class', image: 'assets/blei.png' },
  { name: 'Laufen', gender: 'Female', age: 20, bending: 'Mage', faction: 'Continental Magic Association', birthplace: 'Northern Continent', arc: 'First-Class Mage Exam', mageRank: 'Third-Class', image: 'assets/laufen.png' }
];
