var Unknown = 'Unknown';
var jojoCharacters = [
  ['Jonathan Joestar','Male',20,'Ripple','Joestar Group','Part 1: Phantom Blood','United Kingdom','Human','assets/jonathan-joestar.png'],
  ['Dio Brando','Male',20,'The World','Dio','Part 1: Phantom Blood','United Kingdom','Vampire','assets/dio-brando.png'],
  ['Robert E. O. Speedwagon','Male',25,'Non-Stand user','Joestar Group','Part 1: Phantom Blood','United Kingdom','Human','assets/speedwagon.png'],
  ['Will A. Zeppeli','Male',50,'Ripple','Joestar Group','Part 1: Phantom Blood','Italy','Human','assets/will-zeppeli.png'],
  ['Erina Pendleton','Female',20,'Non-Stand user','Joestar Family','Part 1: Phantom Blood','United Kingdom','Human','assets/erina-pendleton.png'],
  ['Joseph Joestar','Male',18,'Ripple','Joestar Group','Part 2: Battle Tendency','United States','Human','assets/joseph-joestar.png'],
  ['Caesar Anthonio Zeppeli','Male',20,'Ripple','Joestar Group','Part 2: Battle Tendency','Italy','Human','assets/caesar-zeppeli.png'],
  ['Lisa Lisa','Female',50,'Ripple','Joestar Group','Part 2: Battle Tendency','Italy','Human','assets/lisa-lisa.png'],
  ['Esidisi','Male',100000,'Pillar Man','Pillar Men','Part 2: Battle Tendency','Ancient Rome','Pillar Man','assets/esidisi.png'],
  ['Wamuu','Male',100000,'Pillar Man','Pillar Men','Part 2: Battle Tendency','Ancient Rome','Pillar Man','assets/wamuu.png'],
  ['Kars','Male',100000,'Pillar Man','Pillar Men','Part 2: Battle Tendency','Ancient Rome','Ultimate Being','assets/kars.png'],
  ['Rudol von Stroheim','Male',30,'Non-Stand user','Nazi Germany','Part 2: Battle Tendency','Germany','Human','assets/stroheim.png'],
  ['Jotaro Kujo','Male',17,'Star Platinum','Joestar Group','Part 3: Stardust Crusaders','Japan','Human','assets/jotaro-kujo.png'],
  ['Noriaki Kakyoin','Male',17,'Hierophant Green','Stardust Crusaders','Part 3: Stardust Crusaders','Japan','Human','assets/kakyoin.png'],
  ['Jean Pierre Polnareff','Male',22,'Silver Chariot','Stardust Crusaders','Part 3: Stardust Crusaders','France','Human','assets/polnareff.png'],
  ['Muhammad Avdol','Male',30,'Magician’s Red','Stardust Crusaders','Part 3: Stardust Crusaders','Egypt','Human','assets/avdol.png'],
  ['Iggy','Male',5,'The Fool','Stardust Crusaders','Part 3: Stardust Crusaders','United States','Dog','assets/iggy.png'],
  ['Giorno Giovanna','Male',15,'Gold Experience','Passione','Part 5: Golden Wind','Italy','Human','assets/giorno.png'],
  ['Bruno Bucciarati','Male',20,'Sticky Fingers','Passione','Part 5: Golden Wind','Italy','Human','assets/bruno.png'],
  ['Guido Mista','Male',18,'Sex Pistols','Passione','Part 5: Golden Wind','Italy','Human','assets/mista.png'],
  ['Narancia Ghirga','Male',17,'Aerosmith','Passione','Part 5: Golden Wind','Italy','Human','assets/narancia.png'],
  ['Leone Abbacchio','Male',21,'Moody Blues','Passione','Part 5: Golden Wind','Italy','Human','assets/abbacchio.png'],
  ['Trish Una','Female',15,'Spice Girl','Passione','Part 5: Golden Wind','Italy','Human','assets/trish.png'],
  ['Diavolo','Male',33,'King Crimson','Passione','Part 5: Golden Wind','Italy','Human','assets/diavolo.png'],
  ['Enrico Pucci','Male',39,'Whitesnake','Green Dolphin Street Prison','Part 6: Stone Ocean','United States','Human','assets/pucci.png'],
  ['Jolyne Cujoh','Female',19,'Stone Free','Joestar Group','Part 6: Stone Ocean','United States','Human','assets/jolyne.png'],
  ['Ermes Costello','Female',21,'Kiss','Green Dolphin Street Prison','Part 6: Stone Ocean','United States','Human','assets/ermes.png'],
  ['Foo Fighters','Female',1,'Foo Fighters','Jolyne Group','Part 6: Stone Ocean','United States','Plankton colony','assets/foo-fighters.png'],
  ['Weather Report','Male',39,'Weather Report','Jolyne Group','Part 6: Stone Ocean','United States','Human','assets/weather-report.png'],
  ['Narciso Anasui','Male',25,'Diver Down','Jolyne Group','Part 6: Stone Ocean','United States','Human','assets/anasui.png'],
  ['Johnny Joestar','Male',29,'Tusk','Joestar Group','Part 7: Steel Ball Run','United States','Human','assets/johnny.png'],
  ['Gyro Zeppeli','Male',24,'Ball Breaker','Joestar Group','Part 7: Steel Ball Run','Italy','Human','assets/gyro.png'],
  ['Funny Valentine','Male',48,'Dirty Deeds Done Dirt Cheap','United States Government','Part 7: Steel Ball Run','United States','Human','assets/funny-valentine.png'],
  ['Diego Brando','Male',21,'Scary Monsters','Steel Ball Run','Part 7: Steel Ball Run','United Kingdom','Human','assets/diego.png'],
  ['Lucy Steel','Female',14,'Non-Stand user','Steel Ball Run','Part 7: Steel Ball Run','United States','Human','assets/lucy-steel.png'],
  ['Josuke Higashikata','Male',19,'Soft & Wet','Higashikata Family','Part 8: JoJolion','Japan','Human','assets/josuke-higashikata.png'],
  ['Yasuho Hirose','Female',19,'Paisley Park','Higashikata Group','Part 8: JoJolion','Japan','Human','assets/yasuho.png'],
  ['Rai Mamezuku','Male',31,'Doggy Style','Higashikata Group','Part 8: JoJolion','Japan','Human','assets/rai.png'],
  ['Tooru','Male',Unknown,'Wonder of U','Rock Humans','Part 8: JoJolion','Japan','Rock Human','assets/tooru.png'],
  ['Yoshikage Kira','Male',33,'Killer Queen','Morioh','Part 4: Diamond Is Unbreakable','Japan','Human','assets/kira.png'],
  ['Josuke Higashikata (Part 4)','Male',16,'Crazy Diamond','Morioh','Part 4: Diamond Is Unbreakable','Japan','Human','assets/josuke.png'],
  ['Koichi Hirose','Male',15,'Echoes','Morioh Group','Part 4: Diamond Is Unbreakable','Japan','Human','assets/koichi.png'],
  ['Okuyasu Nijimura','Male',15,'The Hand','Morioh Group','Part 4: Diamond Is Unbreakable','Japan','Human','assets/okuyasu.png'],
  ['Rohan Kishibe','Male',20,'Heaven’s Door','Morioh','Part 4: Diamond Is Unbreakable','Japan','Human','assets/rohan.png'],
  ['Mikitaka Hazekura','Male',Unknown,'Earth Wind and Fire','Morioh','Part 4: Diamond Is Unbreakable','Japan','Alien?','assets/mikitaka.png'],
  ['Yukako Yamagishi','Female',16,'Love Deluxe','Morioh Group','Part 4: Diamond Is Unbreakable','Japan','Human','assets/yukako.png'],
  ['Hol Horse','Male',25,'Emperor','Dio’s Agents','Part 3: Stardust Crusaders','United States','Human','assets/hol-horse.png'],
  ['Vanilla Ice','Male',30,'Cream','Dio’s Agents','Part 3: Stardust Crusaders','Egypt','Human','assets/vanilla-ice.png'],
  ['D’Arby the Elder','Male',Unknown,'Osiris','Dio’s Agents','Part 3: Stardust Crusaders','United States','Human','assets/darby-elder.png'],
  ['D’Arby the Younger','Male',Unknown,'Atum','Dio’s Agents','Part 3: Stardust Crusaders','United States','Human','assets/darby-younger.png'],
  ['Pet Shop','Male',Unknown,'Horus','Dio’s Agents','Part 3: Stardust Crusaders','Egypt','Falcon','assets/pet-shop.png'],
  ['Yukako Yamagishi (early)','Female',16,'Love Deluxe','Morioh Group','Part 4: Diamond Is Unbreakable','Japan','Human','assets/yukako-early.png'],
  ['Tomoko Higashikata','Female',39,'Non-Stand user','Higashikata Family','Part 4: Diamond Is Unbreakable','Japan','Human','assets/tomoko.png'],
  ['Reimi Sugimoto','Female',16,'Non-Stand user','Morioh','Part 4: Diamond Is Unbreakable','Japan','Ghost','assets/reimi.png'],
  ['Shigekiyo Yangu','Male',14,'Harvest','Morioh Group','Part 4: Diamond Is Unbreakable','Japan','Human','assets/shigechi.png'],
  ['Tamami Kobayashi','Male',19,'The Lock','Dio’s Agents','Part 4: Diamond Is Unbreakable','Japan','Human','assets/tamami.png'],
  ['Toshikazu Hazamada','Male',15,'Surface','Morioh Group','Part 4: Diamond Is Unbreakable','Japan','Human','assets/hazamada.png'],
  ['Toyohiro Kanedaichi','Male',21,'Super Fly','Morioh','Part 4: Diamond Is Unbreakable','Japan','Human','assets/toyohiro.png'],
  ['Yoshihiro Kira','Male',60,'Atom Heart Father','Kira Family','Part 4: Diamond Is Unbreakable','Japan','Ghost','assets/yoshihiro-kira.png'],
  ['Masazo Kinoto','Male',25,'Cheap Trick','Morioh','Part 4: Diamond Is Unbreakable','Japan','Human','assets/kinoto.png'],
  ['Aya Tsuji','Female',Unknown,'Cinderella','Morioh','Part 4: Diamond Is Unbreakable','Japan','Human','assets/aya.png'],
  ['Pocoloco','Male',21,'Hey Ya!','Steel Ball Run','Part 7: Steel Ball Run','United States','Human','assets/pocoloco.png'],
  ['Hot Pants','Female',23,'Cream Starter','Steel Ball Run','Part 7: Steel Ball Run','United States','Human','assets/hot-pants.png'],
  ['Mountain Tim','Male',31,'Oh! Lonesome Me','Steel Ball Run','Part 7: Steel Ball Run','United States','Human','assets/mountain-tim.png'],
  ['Ringo Roadagain','Male',32,'Mandom','Steel Ball Run','Part 7: Steel Ball Run','United States','Human','assets/ringo.png'],
  ['Blackmore','Male',Unknown,'Catch the Rainbow','United States Government','Part 7: Steel Ball Run','United States','Human','assets/blackmore.png'],
  ['Magent Magent','Male',Unknown,'20th Century Boy','Valentine’s Agents','Part 7: Steel Ball Run','United States','Human','assets/magent.png'],
  ['Wekapipo','Male',Unknown,'Wrecking Ball','Steel Ball Run','Part 7: Steel Ball Run','United States','Human','assets/wekapipo.png'],
  ['Dr. Ferdinand','Male',Unknown,'Scary Monsters','Steel Ball Run','Part 7: Steel Ball Run','United States','Human','assets/ferdinand.png'],
  ['Axl RO','Male',Unknown,'Civil War','Valentine’s Agents','Part 7: Steel Ball Run','United States','Human','assets/axl-ro.png'],
  ['D-I-S-C-O','Male',Unknown,'Chocolate Disco','Valentine’s Agents','Part 7: Steel Ball Run','United States','Human','assets/disco.png'],
  ['Norisuke Higashikata IV','Male',48,'King Nothing','Higashikata Family','Part 8: JoJolion','Japan','Human','assets/norisuke.png'],
  ['Daiya Higashikata','Female',16,'California King Bed','Higashikata Family','Part 8: JoJolion','Japan','Human','assets/daiya.png'],
  ['Hato Higashikata','Female',21,'Walking Heart','Higashikata Family','Part 8: JoJolion','Japan','Human','assets/hato.png'],
  ['Jobin Higashikata','Male',29,'Speed King','Higashikata Family','Part 8: JoJolion','Japan','Human','assets/jobin.png'],
  ['Tsurugi Higashikata','Male',9,'Paper Moon King','Higashikata Family','Part 8: JoJolion','Japan','Human','assets/tsurugi.png'],
  ['Mitsuba Higashikata','Female',31,'Awaking III Leaves','Higashikata Family','Part 8: JoJolion','Japan','Human','assets/mitsuba.png'],
  ['Kaato Higashikata','Female',49,'Space Trucking','Higashikata Family','Part 8: JoJolion','Japan','Human','assets/kaato.png'],
  ['Yagiyama Yotsuyu','Male',Unknown,'I Am a Rock','Rock Humans','Part 8: JoJolion','Japan','Rock Human','assets/yotsuyu.png'],
  ['Aisho Dainenjiyama','Male',Unknown,'Doobie Wah!','Rock Humans','Part 8: JoJolion','Japan','Rock Human','assets/aisho.png'],
  ['Damo Tamaki','Male',Unknown,'Vitamin C','Rock Humans','Part 8: JoJolion','Japan','Rock Human','assets/damo.png'],
  ['Dolomite','Male',Unknown,'Blue Hawaii','Rock Humans','Part 8: JoJolion','Japan','Rock Human','assets/dolomite.png'],
  ['Satoru Akefu','Male',Unknown,'Wonder of U','Rock Humans','Part 8: JoJolion','Japan','Rock Human','assets/akefu.png'],
  ['Johnny Joestar (child)','Male',14,'Tusk','Joestar Family','Part 7: Steel Ball Run','United States','Human','assets/johnny-child.png'],
  ['George Joestar II','Male',18,'Non-Stand user','Joestar Family','Part 2: Battle Tendency','United Kingdom','Human','assets/george-joestar.png'],
  ['Donatella Una','Female',Unknown,'Non-Stand user','Passione','Part 5: Golden Wind','Italy','Human','assets/donatella.png'],
  ['Scolippi','Male',Unknown,'Rolling Stones','Passione','Part 5: Golden Wind','Italy','Human','assets/scolippi.png'],
  ['Risotto Nero','Male',Unknown,'Metallica','La Squadra Esecuzioni','Part 5: Golden Wind','Italy','Human','assets/risotto.png'],
  ['Formaggio','Male',Unknown,'Little Feet','La Squadra Esecuzioni','Part 5: Golden Wind','Italy','Human','assets/formaggio.png'],
  ['Illuso','Male',Unknown,'Man in the Mirror','La Squadra Esecuzioni','Part 5: Golden Wind','Italy','Human','assets/illuso.png'],
  ['Prosciutto','Male',Unknown,'The Grateful Dead','La Squadra Esecuzioni','Part 5: Golden Wind','Italy','Human','assets/prosciutto.png'],
  ['Pesci','Male',Unknown,'Beach Boy','La Squadra Esecuzioni','Part 5: Golden Wind','Italy','Human','assets/pesci.png'],
  ['Melone','Male',Unknown,'Baby Face','La Squadra Esecuzioni','Part 5: Golden Wind','Italy','Human','assets/melone.png'],
  ['Ghiaccio','Male',Unknown,'White Album','La Squadra Esecuzioni','Part 5: Golden Wind','Italy','Human','assets/ghiaccio.png'],
  ['Squalo','Male',Unknown,'Clash','Passione','Part 5: Golden Wind','Italy','Human','assets/squalo.png'],
  ['Tizziano','Male',Unknown,'Talking Head','Passione','Part 5: Golden Wind','Italy','Human','assets/tizziano.png'],
  ['Secco','Male',Unknown,'Oasis','Diavolo’s Agents','Part 5: Golden Wind','Italy','Human','assets/secco.png'],
  ['Cioccolata','Male',Unknown,'Green Day','Diavolo’s Agents','Part 5: Golden Wind','Italy','Human','assets/cioccolata.png'],
  ['Murolo Murolo','Male',Unknown,'Green, Green Grass of Home','Green Dolphin Street Prison','Part 6: Stone Ocean','United States','Human','assets/murolo.png'],
  ['Thunder McQueen','Male',Unknown,'Highway to Hell','Green Dolphin Street Prison','Part 6: Stone Ocean','United States','Human','assets/thunder-mcqueen.png'],
  ['Lang Rangler','Male',Unknown,'Jumpin’ Jack Flash','Green Dolphin Street Prison','Part 6: Stone Ocean','United States','Human','assets/lang-rangler.png'],
  ['Viviano Westwood','Male',Unknown,'Planet Waves','Green Dolphin Street Prison','Part 6: Stone Ocean','United States','Human','assets/westwood.png'],
  ['Kenzou','Male',78,'Dragon’s Dream','Green Dolphin Street Prison','Part 6: Stone Ocean','United States','Human','assets/kenzou.png']
].map(([name, gender, age, stand, faction, part, birthplace, species, image]) => ({ name, gender, age, stand, standType: jojoStandType(stand), faction, part, birthplace, species, image }));
function jojoStandType(stand) {
  if (stand === 'Non-Stand user') return 'No Stand';
  if (['Cream', 'The Hand', 'Crazy Diamond', 'Star Platinum', 'Stone Free', 'Silver Chariot', 'Sticky Fingers', 'The World'].includes(stand)) return 'Close-range power';
  if (['Hierophant Green', 'Emperor', 'Aerosmith', 'Horus', 'Beach Boy', 'Man in the Mirror', 'Whitesnake', 'Weather Report'].includes(stand)) return 'Long-range';
  if (['Harvest', 'Sex Pistols', 'Foo Fighters', 'Black Sabbath', 'Sheer Heart Attack', 'Baby Face'].includes(stand)) return 'Automatic / remote';
  if (['Tusk', 'Gold Experience', 'Killer Queen', 'King Crimson', 'Wonder of U', 'Soft & Wet', 'Diver Down'].includes(stand)) return 'Evolving / versatile';
  return 'Specialist';
}
jojoCharacters.forEach(character => { character.image = `https://tse1.mm.bing.net/th?q=${encodeURIComponent(character.name + ' JoJo')}`; });
window.jojoCharacters = jojoCharacters;